# Generated by Django 6.0.2 on 2026-03-01 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("body", models.TextField()),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост сообщества",
                "verbose_name_plural": "Посты сообщества",
                "ordering": ["-is_pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CommunityComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("is_published", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.communitypost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий сообщества",
                "verbose_name_plural": "Комментарии сообщества",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouncilJoinApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=32)),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("management", "Факультет управления"),
                            ("it", "Факультет информационных технологий"),
                            ("economics", "Факультет экономики и финансов"),
                            ("law", "Юридический факультет"),
                            ("psycho", "Факультет психолого-педагогического образования"),
                            ("center", "Научно-образовательный центр устойчивого развития"),
                            ("college", "Колледж"),
                            ("postgraduate", "Аспирантура"),
                            ("other", "Другое подразделение"),
                        ],
                        max_length=32,
                    ),
                ),
                ("course", models.CharField(blank=True, max_length=20)),
                ("motivation", models.TextField()),
                ("experience", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая"),
                            ("in_review", "На рассмотрении"),
                            ("approved", "Одобрена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("moderation_comment", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="join_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка в студсовет",
                "verbose_name_plural": "Заявки в студсовет",
                "ordering": ["-created_at"],
            },
        ),
    ]
