# Generated by Django 4.2.7 on 2026-03-11 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_userprofile_role_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPostPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pins', to='core.communitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_post_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal post pin',
                'verbose_name_plural': 'Personal post pins',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post')},
            },
        ),
    ]

