# Generated by Django 4.2.7 on 2026-04-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_communitypostpin_options_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_enabled', models.BooleanField(default=False, verbose_name='Режим техобслуживания')),
                ('maintenance_ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ориентировочное окончание')),
            ],
            options={
                'verbose_name': 'Техобслуживание сайта',
                'verbose_name_plural': 'Техобслуживание сайта',
            },
        ),
    ]
