# Generated by Django 4.2.7 on 2026-04-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sitemaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA включена'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='Секрет 2FA (TOTP)'),
        ),
    ]
