# Generated by Django 4.2.7 on 2026-04-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_event_image_url_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_attachments/'),
        ),
    ]
