# Generated by Django 4.2.7 on 2026-04-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_feedbackmessage_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='moderation_attachment',
            field=models.FileField(blank=True, null=True, upload_to='feedback_moderation_attachments/'),
        ),
    ]
